name: OpenWrt Builder #你的工作流名称（yml文件名称）


on:
repository_dispatch:
workflow_dispatch:


env:
REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10 #源码仓库地址
REPO_BRANCH: 2410 #源码分支
FEEDS_CONF: feeds.conf.default
CONFIG_FILE: .config #你的配置文件名
DIY_P1_SH: diy-part1.sh
DIY_P2_SH: diy-part2.sh
UPLOAD_BIN_DIR: false #上传 bin 目录。即包含所有 ipk 文件和固件的目录。默认false
UPLOAD_FIRMWARE: true #上传固件目录。默认true（建议打开，不然编译好没有固件）
UPLOAD_RELEASE: true #上传固件到 releases 。默认false
TZ: Asia/Shanghai
