#
# 版权所有 (c) 2019-2021 P3TERX <https://p3terx.com>
#
# 这是一个开源软件，遵循 MIT 许可证。
# 详情请参阅 /LICENSE。
#
# https://github.com/P3TERX/Actions-OpenWrt
# 文件: .github/workflows/update-checker.yml
# 描述: 源代码更新检查器
#

name: 更新检查器

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_BRANCH: openwrt-24.10

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 18 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: 获取提交哈希值
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: 比较提交哈希值
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: 保存新的提交哈希值
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

    - name: 触发构建
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        repository: ccaicjoy/padavanonly/immortalwrt-mt798x-24.10
        event-type: 源代码更新

    - name: 删除工作流运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
